### ISSUE TITLE
Update runtime to 23.08

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.pjbroad.EternallandsClient#28]
Consider updating the runtime used by this Flatpak to 23.08.

**Comment by pjbroad** [comment]
Unfortunately, 23.08 uses libxml 2.11 which included breaking changed for EL.  Later versions include a fix that works fine.  Unfortunately, the code will never build on that specific version.

**Comment by pjbroad** [comment]
I've updated the beta branch to run-time 23.08 and included a local build of the latest libxml2 to fix the above issue.
